import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { authenticateApiKey } from '@/lib/api-keys'
import { getLocalizedField } from '@/lib/i18n/get-localized-field'
import { locales, type Locale } from '@/lib/i18n/config'
import { getSiteUrl } from '@/lib/site-url'

/**
 * GET /api/v1/trips/latest
 *
 * Partner-facing feed of the most recently created trips, authenticated with
 * an API key issued in the admin dashboard (Authorization: Bearer <key>).
 *
 * Custom trips are excluded by default. A trip with `is_custom = true` is
 * generated by the admin custom-booking flow for one named customer, is
 * attached to that customer's inquiry, and is hidden from every public listing
 * on the site — so the default filter matches the public pages exactly
 * (`.neq('is_custom', true)`).
 *
 * `include_custom=true` lifts that filter, but only for keys an admin has
 * granted `allow_custom_trips`. Both gates are needed on purpose: the
 * parameter lets a permitted partner choose per request, while the flag keeps
 * the decision to expose private bookings with 4SG Tour rather than with the
 * partner. Every trip carries `is_custom` so a caller can tell them apart.
 */

export const dynamic = 'force-dynamic'

const DEFAULT_LIMIT = 10
const MAX_LIMIT = 50

export async function GET(request: Request) {
  const auth = await authenticateApiKey(request)

  if (!auth.ok) {
    return NextResponse.json(
      { error: auth.error, code: auth.code },
      { status: auth.status, headers: { 'Cache-Control': 'no-store' } },
    )
  }

  try {
    const { searchParams } = new URL(request.url)

    const limitParam = searchParams.get('limit')
    let limit = DEFAULT_LIMIT

    if (limitParam !== null) {
      const parsed = Number(limitParam)
      if (!Number.isInteger(parsed) || parsed < 1 || parsed > MAX_LIMIT) {
        return NextResponse.json(
          {
            error: `limit must be an integer between 1 and ${MAX_LIMIT}.`,
            code: 'invalid_limit',
          },
          { status: 400 },
        )
      }
      limit = parsed
    }

    const localeParam = searchParams.get('locale')
    if (localeParam !== null && !locales.includes(localeParam as Locale)) {
      return NextResponse.json(
        {
          error: `locale must be one of: ${locales.join(', ')}.`,
          code: 'invalid_locale',
        },
        { status: 400 },
      )
    }
    const locale = (localeParam as Locale) || 'en'

    const sinceParam = searchParams.get('since')
    if (sinceParam !== null && Number.isNaN(Date.parse(sinceParam))) {
      return NextResponse.json(
        {
          error: 'since must be an ISO 8601 timestamp, e.g. 2026-08-01T00:00:00Z.',
          code: 'invalid_since',
        },
        { status: 400 },
      )
    }

    const includeCustomParam = searchParams.get('include_custom')
    if (
      includeCustomParam !== null &&
      includeCustomParam !== 'true' &&
      includeCustomParam !== 'false'
    ) {
      return NextResponse.json(
        {
          error: 'include_custom must be either true or false.',
          code: 'invalid_include_custom',
        },
        { status: 400 },
      )
    }
    const includeCustom = includeCustomParam === 'true'

    // Refuse loudly rather than silently downgrading to the default — a
    // partner who thinks they are receiving custom trips and is not should
    // find that out on the first call, not from a gap in their catalogue.
    if (includeCustom && !auth.apiKey.allowCustomTrips) {
      return NextResponse.json(
        {
          error:
            'This API key is not permitted to read custom trips. Contact 4SG Tour to have it enabled.',
          code: 'custom_trips_not_permitted',
        },
        { status: 403, headers: { 'Cache-Control': 'no-store' } },
      )
    }

    const continent = searchParams.get('continent')

    // Service-role: the caller has no Supabase session, and this route has
    // already established who they are from their API key.
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
    )

    let query = supabase
      .from('trips')
      .select(
        `
        *,
        packages(id, name, name_ko, name_de, description, description_ko, description_de, price, availability, quantity, participants_per_booking),
        trip_images(image_url, display_order)
      `,
      )
      .order('created_at', { ascending: false })
      .limit(limit)

    if (!includeCustom) {
      // Same filter the public pages use, so the feed and the site agree.
      query = query.neq('is_custom', true)
    }

    if (continent) {
      query = query.eq('continent', continent)
    }

    if (sinceParam) {
      query = query.gt('created_at', new Date(sinceParam).toISOString())
    }

    const { data: trips, error } = await query

    if (error) throw error

    const siteUrl = getSiteUrl()

    const data = (trips || []).map((trip) => {
      const images = ((trip.trip_images as
        | Array<{ image_url: string; display_order: number }>
        | null) || [])
        .slice()
        .sort((a, b) => a.display_order - b.display_order)
        .map((image) => image.image_url)

      const packages = ((trip.packages as
        | Array<Record<string, unknown>>
        | null) || []).map((pkg) => ({
        id: pkg.id as string,
        name: getLocalizedField(pkg, 'name', locale),
        description: getLocalizedField(pkg, 'description', locale) || null,
        price: pkg.price as number,
        availability: pkg.availability as string,
        quantity: (pkg.quantity as number | null) ?? null,
        participants_per_booking: pkg.participants_per_booking as number,
      }))

      return {
        id: trip.id as string,
        slug: trip.slug as string,
        url: `${siteUrl}/trips/${trip.slug}`,
        title: getLocalizedField(trip, 'title', locale),
        description: getLocalizedField(trip, 'description', locale) || null,
        overview_content:
          getLocalizedField(trip, 'overview_content', locale) || null,
        highlights: getLocalizedField(trip, 'highlights', locale, true),
        location: getLocalizedField(trip, 'location', locale),
        continent: (trip.continent as string | null) ?? null,
        is_custom: trip.is_custom === true,
        price_regular: trip.price_regular as number,
        show_from_price: trip.show_from_price as boolean,
        deposit_percentage: (trip.deposit_percentage as number | null) ?? null,
        max_guests: trip.max_guests as number,
        min_days: trip.min_days as number,
        max_days: (trip.max_days as number | null) ?? null,
        min_days_advance: trip.min_days_advance as number,
        refund_policy: getLocalizedField(trip, 'refund_policy', locale) || null,
        images,
        courses_photo_url: (trip.courses_photo_url as string | null) ?? null,
        room_photo_url: (trip.room_photo_url as string | null) ?? null,
        packages,
        created_at: trip.created_at as string,
        updated_at: trip.updated_at as string,
      }
    })

    return NextResponse.json(
      {
        data,
        meta: {
          count: data.length,
          limit,
          locale,
          currency: 'USD',
          include_custom: includeCustom,
          // Feed a `since` on the next call to page forward through new trips.
          latest_created_at: data[0]?.created_at ?? null,
        },
      },
      { headers: { 'Cache-Control': 'no-store' } },
    )
  } catch (error) {
    console.error('[api/v1/trips/latest] Error fetching trips:', error)
    return NextResponse.json(
      { error: 'Failed to fetch trips', code: 'server_error' },
      { status: 500 },
    )
  }
}
